config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: "posts#index"

  resources :posts do
    resources :comments
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_attached_file :image, styles: { thumb: "180x180#", standard: "250x250#"}, default_url: "/images/:style/missing.jpeg"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/

  has_many :comments, dependent: :destroy
  validates :name, length: { minimum: 3 }
end

app/models/user.rb
class User < ActiveRecord::Base


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new
  end

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create(comment_params)
    redirect_to posts_path
  end

  def comment_params
    params.require(:comment).permit(:thoughts)
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.create(post_params)
    if @post.save
      redirect_to posts_path
    else
      render 'new'
    end
  end

  def post_params
    params.require(:post).permit(:name, :image)
  end

  def show
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    flash[:notice] = "Confound these ponies! Your post is destroyed."
    redirect_to '/posts'
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :thoughts %>
  <%= f.text_area :thoughts %>
  <%= f.submit 'Post comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyLittlePhoti</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">
        <a class="navbar-brand" href="#">
          <img class="logo" alt="Brand" src="/images/mylittlephoti.png">
        </a>
      </div>
      <h1 class="mylittlephoti">MyLittlePhoti</h1>
      <% if user_signed_in? %>
        <p class="navbar-text navbar-right"><%= link_to "Sign out", destroy_user_session_path, method: :delete %></p>
      <% else %>
        <p class="navbar-text navbar-right"><%= link_to "Sign in", new_user_session_path %></p>
        <p class="navbar-text navbar-right"><%= link_to "Sign up", new_user_registration_path %></p>
      <% end %>
    </div>
  </nav>

  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>


<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<% if @posts.any? %>
  <% @posts.each do |post| %>
    <%= link_to (image_tag post.image.url(:thumb)), post_path(post) %>
    <h2><%= link_to "#{post.name}", post_path(post) %></h2>
    <p><%= link_to "Comment on #{post.name}", new_post_comment_path(post) %></p>
    <% if post.comments.any? %>
      <% post.comments.each do |comment| %>
        <li><%= comment.thoughts %></li>
      <% end %>
    <% else %>
      No comments.
    <% end %>
    <p><%= link_to "Delete #{post.name}", post_path(post), method: :delete %></p>
  <% end %>
<% else %>
  No posts!
<% end %>

<a href="/posts/new">Create a Post</a>

app/views/posts/new.html.erb
<% if @post.errors.any? %>
  <div id="errors">
    <h2><%= pluralize(@post.errors.count, "error") %> stopped your post from being saved</h2>
    <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @post, html: {multipart: true} do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.file_field :image %>
  <%= f.submit %>

<% end %>

app/views/posts/show.html.erb
<div class="posts">
  <%= image_tag @post.image.url(:standard) %>
  <%= @post.name %>

  <% if @post.comments.any? %>
    <% @post.comments.each do |comment| %>
      <li><%= comment.thoughts %></li>
    <% end %>
  <% else %>
    No comments.
  <% end %>
</div>